### ISSUE TITLE
Writing is always stuck on 0%

### ISSUE THREAD

**Issue by SjorsVanGelderen** [mikeryan/ems-flasher#15]
The command
`sudo ./ems-flasher --verbose --write romname.gb`

always results in:
`trying to find EMS cart
claimed EMS cart
base address is 0x0
Loading the menu ROM...Writing /usr/share/ems-flasher/menu.gb [MENU#]...
    0% 00:12`

and it never continues from there.

I'm running Ubuntu 16.04.1 LTS 64 bit.

**Comment by chastai** [comment]
Hi,
Could you run the command with debug log enabled?
`sudo LIBUSB_DEBUG=4 ./ems-flasher --verbose --write romname.gb`

Also, to avoid running the program as root you can follow theses instructions: http://lacklustre.net/projects/ems-flasher/faq.html (the second method is preferable)

**Comment by SjorsVanGelderen** [comment]
I'm attaching the log. Keep in mind that eventually I just pull the cable because nothing is happening and I need to interrupt the process; this is why the flashing suddenly fails.
The game that's already on the device works without problems, but the new ROM is not flashed.
It's just stuck in that `[libusb_handle_events_timeout_completed] doing our own event handling
[ 1.082572] [00001cc2] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[61.105088] [00001cc2] libusb: debug [handle_events] poll() returned 0
` loop.

[log.txt](https://github.com/mikeryan/ems-flasher/files/466255/log.txt)

**Comment by chastai** [comment]
I see. It stalls when trying to erase the first erase-block. Maybe that the block is defective or locked or the limit of 100 000 erase cycles has been reached.

Or it may be a bug in ems-flasher of course. Let's see if other erase-blocks can be flashed:
 - Arrange to flash a ROM on an other erase-block on the same page (an erase-block is 128K or 8 banks of 16K). E.g. flash a ROM of 128KB compatible with the menu so that the first block is left alone (i.e. if the menu is a GBC one, add a GBC ROM).
 - Try to format and to flash some ROMs on the second page.

Of course, you should also test the card with another OS or an older version of ems-flasher or the official flasher from EMS.

**Comment by SjorsVanGelderen** [comment]
I discovered the problem. The cartridge doesn't allow flashing if it's inside a Game Boy; even if the Game Boy is powered off. Sorry about wasting your time with this!

**Comment by chastai** [comment]
No problem ;-)
